# Generated by Django 3.1 on 2020-08-11 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bodytype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pdapp.bodytype'),
        ),
        migrations.AddField(
            model_name='product',
            name='lenstype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pdapp.lenstype'),
        ),
    ]
