# Generated by Django 3.1 on 2020-08-14 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdapp', '0002_auto_20200811_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='star',
        ),
        migrations.AlterField(
            model_name='product',
            name='bodytype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdapp.bodytype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lenstype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdapp.lenstype'),
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField(null=True)),
                ('pdname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdapp.product')),
            ],
        ),
    ]
