# Generated by Django 3.1 on 2020-08-14 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdapp', '0002_auto_20200811_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bodytype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdapp.bodytype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lenstype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdapp.lenstype'),
        ),
    ]
