# Generated by Django 3.1 on 2020-08-14 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdapp', '0003_auto_20200814_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='star',
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField(null=True)),
                ('pdname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdapp.product')),
            ],
        ),
    ]
