# Generated by Django 3.1 on 2020-08-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdapp', '0006_auto_20200814_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdtype', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='star',
            options={'ordering': ['-star']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='bodytype',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lenstype',
        ),
    ]
