# Generated by Django 3.1 on 2020-08-14 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdapp', '0006_auto_20200814_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='star',
            old_name='pdname',
            new_name='pdstar',
        ),
    ]
