# Generated by Django 3.1 on 2020-08-18 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdapp', '0007_auto_20200818_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pdapp.type'),
        ),
    ]
