# Generated by Django 3.1 on 2020-08-18 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdapp', '0008_product_pdtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='pdtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pdapp.type'),
        ),
    ]
