# Generated by Django 3.1 on 2020-08-18 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdapp', '0009_star_pdtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='star',
            options={},
        ),
    ]
