<<<<<<< HEAD:CP/mainapp/migrations/0002_auto_20200820_2349.py
# Generated by Django 3.1 on 2020-08-20 14:49
=======
# Generated by Django 3.1 on 2020-08-20 14:47
>>>>>>> 2bde52a54a90594cc707e11c1450b48caaf25289:CP/mainapp/migrations/0002_auto_20200820_2347.py

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
        ('pdapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buy',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdapp.product'),
        ),
        migrations.AddField(
            model_name='buy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='album',
            name='bodypd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bodypd', to='pdapp.product'),
        ),
        migrations.AddField(
            model_name='album',
            name='lenspd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lenspd', to='pdapp.product'),
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
