# Generated by Django 3.1 on 2020-08-18 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdapp', '0008_product_pdtype'),
        ('mainapp', '0003_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='bodypd',
        ),
        migrations.RemoveField(
            model_name='album',
            name='lenspd',
        ),
        migrations.AddField(
            model_name='album',
            name='pdtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pdapp.type'),
        ),
    ]
