# Generated by Django 3.1 on 2020-08-18 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdapp', '0008_product_pdtype'),
        ('mainapp', '0004_auto_20200818_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='pdtype',
        ),
        migrations.AddField(
            model_name='album',
            name='bodypd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bodypd', to='pdapp.product'),
        ),
        migrations.AddField(
            model_name='album',
            name='lenspd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lenspd', to='pdapp.product'),
        ),
    ]
