# Generated by Django 3.1 on 2020-08-11 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdapp', '0002_auto_20200811_1425'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mypd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdapp.product')),
            ],
        ),
    ]
